server:
  port: 80
spring:
  application:
    name: eureka-consumer-ribbon
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1001/eureka