server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        input:
          group: Service-A
          destination:  greetings
          consumer:
            partitioned: true
      instance-count: 2
      instance-index: 1