server:
  port: 2001
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:1001/eureka
  instance:
    prefer-ip-address: true
    instance-id: myeureka-client-2001
info:
  applicationname: ${spring.application.name}
  server.port: ${server.port}