
server:
  port: 9002
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XuKK-OUC/sringcloud-config-learning.git
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
